version: 2.1
executors:
  fedora:
    docker:
      - image: registry.fedoraproject.org/fedora
    shell: /usr/bin/bash

jobs:
  build-linux:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            gcc git make python3-rcssmin sed
            libmicrohttpd-devel libX11-devel sqlite-devel
      - checkout
      - run:
          name: Build
          command: >
            make -j
      - persist_to_workspace:
          root: build/
          paths: taymtrakka
  build-windows:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            git make python3-rcssmin sed
            mingw64-gcc mingw64-libmicrohttpd mingw64-sqlite
      - checkout
      - run:
          name: Checkout git submodules
          command: >
            git submodule init && git submodule update
      - run:
          name: Modify LDLIBS
          command: >
            sed -e 's/-lX11/-lmingw32/' -i Makefile
      - run:
          name: Build
          command: >
            CC=x86_64-w64-mingw32-gcc
            make -j
      - persist_to_workspace:
          root: build/
          paths: taymtrakka.exe
  bundle:
    executor: fedora
    steps:
      - run:
          name: Install dependencies
          command: >
            sudo dnf install --assumeyes --setopt=install_weak_deps=False
            git wget zip
            libmicrohttpd-devel libX11-devel sqlite-devel
            mingw64-libmicrohttpd mingw64-sqlite
      - run:
          name: Install copydeps
          command: |
            sudo dnf install dnf-plugins-core --assumeyes
            sudo dnf copr enable suve/copydeps --assumeyes
            sudo dnf install copydeps --assumeyes
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build Linux bundle
          command: >
            mkdir -pv build/taymtrakka
            && cp -av /tmp/workspace/taymtrakka build/taymtrakka/
            && copydeps --verbose build/taymtrakka/taymtrakka
            && pushd build
            && zip -9 -r taymtrakka-linux64.zip taymtrakka/
            && popd
            && rm -rf build/taymtrakka
      - run:
          name: Build Windows bundle
          command: >
            mkdir -pv build/taymtrakka
            && cp -av /tmp/workspace/taymtrakka.exe build/taymtrakka/
            && copydeps --verbose build/taymtrakka/taymtrakka.exe
            && pushd build
            && zip -9 -r taymtrakka-win64.zip taymtrakka/
            && popd
            && rm -rf build/taymtrakka
      - store_artifacts:
          path: build/

workflows:
  build:
    jobs:
      - build-linux
      - build-windows
      - bundle:
          requires:
            - build-linux
            - build-windows
