PRAGMA page_size = 4096;

CREATE TABLE IF NOT EXISTS "windows" (
	"wnd_id" INTEGER PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
	"wnd_name" TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS "datapoints" (
	"dp_id" INTEGER PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
	"dp_wnd_id" INTEGER,
	"dp_start" INTEGER,
	"dp_end" INTEGER
);

CREATE TABLE IF NOT EXISTS "labels" (
	"lbl_id" INTEGER PRIMARY KEY ASC ON CONFLICT FAIL AUTOINCREMENT,
	"lbl_name" TEXT,
	"lbl_regex" TEXT
);

